name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}      
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Setup NuGet.exe for use with actions
      uses: NuGet/setup-nuget@v1.0.5
      with:
        PROJECT_FILE_PATH: Jorgelig.HttpClient/Jorgelig.HttpClient.csproj
        TAG: '*'
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
